config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'landing#show'
  devise_for :users
  resources :landing, only: [:show]
  resources :dashboard
  resources :histories
  resources :devices
  resources :peripherals
  resources :colaborators
  resources :headquarters
  resources :types
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/colaborator.rb
# frozen_string_literal: true

class Colaborator < ApplicationRecord
  validates :name, presence: true
  validates :lastname, presence: true
  validates :status, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :adress, presence: true
  validates :phone, presence: true, uniqueness: true, format: { with: /\A[0-9]{10,11}\z/ }
end

app/models/device.rb
# frozen_string_literal: true

class Device < ApplicationRecord
  validates :serial, presence: true
  validates :model, presence: true
  validates :processor, presence: true
  validates :memory, presence: true
  validates :storage, presence: true
  validates :status, presence: true
  belongs_to :headquarter
  belongs_to :colaborator
end

app/models/headquarter.rb
# frozen_string_literal: true

class Headquarter < ApplicationRecord
  validates :name, presence: true
  validates :adress, presence: true
end

app/models/history.rb
# frozen_string_literal: true

class History < ApplicationRecord
  belongs_to :colaborator
  belongs_to :device
  belongs_to :peripheral
end

app/models/peripheral.rb
# frozen_string_literal: true

class Peripheral < ApplicationRecord
  belongs_to :type
  belongs_to :colaborator
  belongs_to :headquarter
  validates :status, presence: true
end

app/models/type.rb
# frozen_string_literal: true

class Type < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :name, presence: true
  validates :lastname, presence: true
end

app/controllers/types_controller.rb
# frozen_string_literal: true

class TypesController < ApplicationController
  before_action :set_type, only: %i[show edit update destroy]

  # GET /types or /types.json
  def index
    @types = Type.all
  end

  # GET /types/1 or /types/1.json
  def show; end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit; end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to type_url(@type), notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to type_url(@type), notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_type
    @type = Type.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def type_params
    params.require(:type).permit(:name)
  end
end

app/controllers/users_controller.rb
class Users::SessionsController < Devise::SessionsController
    before_action :authenticate_user!
    # GET /resource/sign_in
    # def new
    #   super
    # end
    ...
  end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/colaborators_helper.rb
# frozen_string_literal: true

module ColaboratorsHelper
end

app/helpers/dasboard_helper.rb
module DasboardHelper
    def pretty_status (status)
        return "Assigned" if status 

        "Available"
    end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
  def pretty_status(status)
    return 'Assigned' if status

    'Available'
  end

  def tabs(tools)
    if tools.instance_of? Device
      render 'relational_table', devices: @tools
    else
      render 'peripheral_table', peripherals: @tools
    end
  end
end

app/helpers/devices_helper.rb
# frozen_string_literal: true

module DevicesHelper
  def colaborators_options
    Colaborator.all.map do |c|
      ["#{c.lastname} #{c.name}", c.id]
    end
  end
end

app/helpers/headquarters_helper.rb
# frozen_string_literal: true

module HeadquartersHelper
end

app/helpers/histories_helper.rb
# frozen_string_literal: true

module HistoriesHelper
end

app/helpers/landing_helper.rb
# frozen_string_literal: true

module LandingHelper
end

app/helpers/peripherals_helper.rb
# frozen_string_literal: true

module PeripheralsHelper
  def colaborators_options
    Colaborator.all.map do |c|
      ["#{c.lastname} #{c.name}", c.id]
    end
  end
end

app/helpers/types_helper.rb
# frozen_string_literal: true

module TypesHelper
end

app/views/shared/_navbar.html.erb
<header>
    <div>
        <nav class="bg-white border-gray-200 dark:bg-gray-900">
            <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl p-4">
                <%= link_to root_path, class: "flex items-center" do %>
                    <%=image_tag ("navbar/inventory"), class: "h-8 mr-3", alt: "inventory Logo" %>
                    <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Inventor.io</span>
                    <% end %>
                <div class="flex items-center">
                    <%if user_signed_in?%>
                        <p class="mr-6 text-sm  text-gray-500 dark:text-white hover:underline"><%=current_user.name %></p>
                        <%= button_to 'Logout', destroy_user_session_path, method: :delete, class:"text-sm  text-blue-600 dark:text-blue-500 hover:underline"%>
                    <% else %>
                        <%= link_to 'Sing In',new_user_session_path, class:"text-sm  text-blue-600 dark:text-blue-500 hover:underline mr-4"%>
                        <a href="#" class="text-sm  text-blue-600 dark:text-blue-500 hover:underline">contact</a>
                    <%end%> 
                </div>
            </div>
        </nav>
        <%if user_signed_in?%>
            <nav class="bg-gray-50 dark:bg-gray-700">
                <button data-collapse-toggle="navbar-dropdown" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-dropdown" aria-expanded="false">
                        <span class="sr-only">Dashbioard menu</span>
                        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                        </svg>
                </button>
                <div class="hidden w-full md:block md:w-auto" id="navbar-dropdown">
                    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                        <li>
                            <%= link_to 'Home', dashboard_index_path, class:"block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500 dark:bg-blue-600 md:dark:bg-transparent", aria:{current: :page} %> 
                        </li>
                        <li>
                            <button id="dropdownNavbarLinkColaborators" data-dropdown-toggle="dropdownNavbarColaborators" class="flex items-center justify-between w-full py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto dark:text-white md:dark:hover:text-blue-500 dark:focus:text-white dark:border-gray-700 dark:hover:bg-gray-700 md:dark:hover:bg-transparent">Colaborators <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                            </svg></button>
                                <!-- Dropdown menu Colaborators-->
                            <div id="dropdownNavbarColaborators" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
                                <ul class="py-2 text-sm text-gray-700 dark:text-gray-400" aria-labelledby="dropdownLargeButton">
                                    <li>
                                        <%= link_to 'Show Colaborators',colaborators_path %>
                                    </li>
                                    <li>
                                        <%= link_to 'Add colaborator',new_colaborator_path %>
                                    </li>
                                    <li>
                                        <%= link_to 'Edit Colaborators',new_colaborator_path %>
                                    </li>
                                </ul>
                                <div class="py-1">
                                    <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">Delete Colaborator</a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <button id="dropdownNavbarLinkHeadquarters" data-dropdown-toggle="dropdownNavbarHeadquarters" class="flex items-center justify-between w-full py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto dark:text-white md:dark:hover:text-blue-500 dark:focus:text-white dark:border-gray-700 dark:hover:bg-gray-700 md:dark:hover:bg-transparent">Headquarters <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                            </svg></button>
                            <!-- Dropdown menu Headquarters-->
                            <div id="dropdownNavbarHeadquarters" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
                                <ul class="py-2 text-sm text-gray-700 dark:text-gray-400" aria-labelledby="dropdownLargeButton">
                                    <li>
                                        <%= link_to 'Show Headquarters',headquarters_path %>
                                    </li>
                                    <li>
                                        <%= link_to 'Add Headquarter',new_headquarter_path %>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="#" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">History</a>
                        </li>
                        <li>
                            <a href="#" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Reports</a>
                        </li>
                    </ul>
                </div>
            </nav>
        <%end%>  
    </div>
</header>