config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'landing#show'
  devise_for :users
  resources :landing, only: [:show]
  resources :dashboard
  resources :histories
  resources :devices
  resources :peripherals
  resources :colaborators
  resources :headquarters
  resources :types
end

app/models/history.rb
# frozen_string_literal: true

class History < ApplicationRecord
  belongs_to :colaborator
  belongs_to :device
  belongs_to :peripheral
end

app/controllers/histories_controller.rb
# frozen_string_literal: true

class HistoriesController < ApplicationController
  before_action :set_history, only: %i[show edit update destroy]

  # GET /histories or /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1 or /histories/1.json
  def show; end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit; end

  # POST /histories or /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to history_url(@history), notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1 or /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to history_url(@history), notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1 or /histories/1.json
  def destroy
    @history.destroy

    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_history
    @history = History.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def history_params
    params.require(:history).permit(:colaborator_id, :device_id, :peripheral_id, :notes, :date)
  end
end

app/helpers/histories_helper.rb
# frozen_string_literal: true

module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history) do |form| %>
  <% if history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
        <% history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :colaborator_id, style: "display: block" %>
    <%= form.text_field :colaborator_id %>
  </div>

  <div>
    <%= form.label :device_id, style: "display: block" %>
    <%= form.text_field :device_id %>
  </div>

  <div>
    <%= form.label :peripheral_id, style: "display: block" %>
    <%= form.text_field :peripheral_id %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/histories/_history.html.erb
<div id="<%= dom_id history %>">
  <p>
    <strong>Colaborator:</strong>
    <%= history.colaborator_id %>
  </p>

  <p>
    <strong>Device:</strong>
    <%= history.device_id %>
  </p>

  <p>
    <strong>Peripheral:</strong>
    <%= history.peripheral_id %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= history.notes %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= history.date %>
  </p>

</div>

app/views/histories/edit.html.erb
<h1>Editing history</h1>

<%= render "form", history: @history %>

<br>

<div>
  <%= link_to "Show this history", @history %> |
  <%= link_to "Back to histories", histories_path %>
</div>

app/views/histories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Histories</h1>

<div id="histories">
  <% @histories.each do |history| %>
    <%= render history %>
    <p>
      <%= link_to "Show this history", history %>
    </p>
  <% end %>
</div>

<%= link_to "New history", new_history_path %>

app/views/histories/new.html.erb
<h1>New history</h1>

<%= render "form", history: @history %>

<br>

<div>
  <%= link_to "Back to histories", histories_path %>
</div>

app/views/histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @history %>

<div>
  <%= link_to "Edit this history", edit_history_path(@history) %> |
  <%= link_to "Back to histories", histories_path %>

  <%= button_to "Destroy this history", @history, method: :delete %>
</div>