config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'landing#show'
  devise_for :users
  resources :landing, only: [:show]
  resources :dashboard
  resources :histories
  resources :devices
  resources :peripherals
  resources :colaborators
  resources :headquarters
  resources :types
end

app/models/headquarter.rb
# frozen_string_literal: true

class Headquarter < ApplicationRecord
  validates :name, presence: true
  validates :adress, presence: true
end

app/controllers/headquarters_controller.rb
# frozen_string_literal: true

class HeadquartersController < ApplicationController
  before_action :set_headquarter, only: %i[show edit update destroy]

  # GET /headquarters or /headquarters.json
  def index
    @headquarters = Headquarter.all
  end

  # GET /headquarters/1 or /headquarters/1.json
  def show; end

  # GET /headquarters/new
  def new
    @headquarter = Headquarter.new
  end

  # GET /headquarters/1/edit
  def edit; end

  # POST /headquarters or /headquarters.json
  def create
    @headquarter = Headquarter.new(headquarter_params)

    respond_to do |format|
      if @headquarter.save
        format.html { redirect_to headquarter_url(@headquarter), notice: 'Headquarter was successfully created.' }
        format.json { render :show, status: :created, location: @headquarter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @headquarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /headquarters/1 or /headquarters/1.json
  def update
    respond_to do |format|
      if @headquarter.update(headquarter_params)
        format.html { redirect_to headquarter_url(@headquarter), notice: 'Headquarter was successfully updated.' }
        format.json { render :show, status: :ok, location: @headquarter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @headquarter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /headquarters/1 or /headquarters/1.json
  def destroy
    @headquarter.destroy

    respond_to do |format|
      format.html { redirect_to headquarters_url, notice: 'Headquarter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_headquarter
    @headquarter = Headquarter.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def headquarter_params
    params.require(:headquarter).permit(:name, :adress)
  end
end

app/helpers/headquarters_helper.rb
# frozen_string_literal: true

module HeadquartersHelper
end

app/views/headquarters/_form.html.erb
<%= form_with(model: headquarter) do |form| %>
  <% if headquarter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(headquarter.errors.count, "error") %> prohibited this headquarter from being saved:</h2>

      <ul>
        <% headquarter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :adress, style: "display: block" %>
    <%= form.text_field :adress %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/headquarters/_headquarter.html.erb
<div id="<%= dom_id headquarter %>">
  <p>
    <strong>Name:</strong>
    <%= headquarter.name %>
  </p>

  <p>
    <strong>Adress:</strong>
    <%= headquarter.adress %>
  </p>

</div>

app/views/headquarters/edit.html.erb
<h1>Editing headquarter</h1>

<%= render "form", headquarter: @headquarter %>

<br>

<div>
  <%= link_to "Show this headquarter", @headquarter %> |
  <%= link_to "Back to headquarters", headquarters_path %>
</div>

app/views/headquarters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Headquarters</h1>

<div id="headquarters">
  <% @headquarters.each do |headquarter| %>
    <%= render headquarter %>
    <p>
      <%= link_to "Show this headquarter", headquarter %>
    </p>
  <% end %>
</div>

<%= link_to "New headquarter", new_headquarter_path %>

app/views/headquarters/new.html.erb
<h1>New headquarter</h1>

<%= render "form", headquarter: @headquarter %>

<br>

<div>
  <%= link_to "Back to headquarters", headquarters_path %>
</div>

app/views/headquarters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @headquarter %>

<div>
  <%= link_to "Edit this headquarter", edit_headquarter_path(@headquarter) %> |
  <%= link_to "Back to headquarters", headquarters_path %>

  <%= button_to "Destroy this headquarter", @headquarter, method: :delete %>
</div>